version: "3"

services:
  job-portal:
    container_name: job-portal
    image: "job-portal"
    build: .
      # context: .
      # dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .key.env
      - .app.postgres.env
      - .app.redis.env
      - .app.otp.env
    depends_on:
      - postgres
      - redis
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .redis.env
    restart: always
  # smtp:
  #   container_name: smtp
  #   image: smtp
  #   ports:
  #     - "587:587"
  #   env_file:
  #     - .otp.env
  #   restart: always

volumes:
  postgres-data:
