version: "3"

services:
  job-portal:
    container_name: job-portal
    image: "job-portal"
    build: .
      # context: .
      # dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .app.postgres.env
      - .app.redis.env
    depends_on:
      - postgres
      - redis
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .postgres.env
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .redis.env
    restart: always
